### ISSUE TITLE
problem with logger

### ISSUE THREAD

**Issue by shonsaraf** [Er-Simon/Telegram-Member-Booster#1]
![image](https://github.com/user-attachments/assets/c73a1c73-3f8e-4340-aec5-cec5522bb018)

**Comment by Er-Simon** [comment]
Thank you for reporting this issue! It appears to be related to the operating system, specifically Windows, as the file name contains the character ':' which is not allowed on this system. I'll work on resolving this and will keep you updated. Thanks again for bringing this to my attention!

**Comment by Er-Simon** [comment]
I've updated the date and time format to avoid compatibility issues on Windows, and I believe this should solve the problem. Since I currently don’t have access to a Windows environment, I would appreciate it if you could test it on your side and let me know if it works as expected. Once I get confirmation, I will proceed to close this issue. Thank you for your help!

**Comment by Er-Simon** [comment]
I've tested the fix on Windows 10, and I can confirm that the issue with the : character in the file name is now resolved. Everything works as expected. I'll proceed to close this issue.
